### ISSUE TITLE
Ansible verion doesn't recognize `package`

### ISSUE THREAD

**Issue by christianh814** [myllynen/openshift-ha-load-balancer#1]
Doesn't look like `package` is a known parameter

```
[chernand@chernand openshift-ha-load-balancer]$ ansible --version
ansible 1.9.6
  configured module search path = None
[chernand@chernand openshift-ha-load-balancer]$ ansible-playbook -i ansible.hosts lb-ha-setup.yml
ERROR: package is not a legal parameter in an Ansible task or handler
```

**Comment by myllynen** [comment]
Thanks for the report. The package module (https://docs.ansible.com/ansible/package_module.html) was introduced in Ansible 2.0 and since OCP 3.4+ comes with Ansible 2.2 or newer I'm going to close this issue. A quick fix for older Ansible versions would be use the yum module instead.
